### ISSUE TITLE
function evaluate()

### ISSUE THREAD

**Issue by KDolos** [KIT-IfGG/NFItools#9]
check if function dismo:evaluate() works for all types of fitted models. Or if we need our own.

**Comment by KDolos** [comment]
does not! added function for threshold calc based on kappa. Other options need to be added - if we do not find a function elsewhere?
Check, if function works for everybody.

**Comment by KDolos** [comment]
What about SDMTools:optim.thresh()?

**Comment by kevDT** [comment]
This function seems to work; is maxKappa the threshold I should apply ?

**Comment by KDolos** [comment]
yes :-)

**Comment by KDolos** [comment]
maybe best is to delete the func. let's see.
